/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as CrowdRouteImport } from './routes/crowd'
import { Route as IndexRouteImport } from './routes/index'

const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdRoute = CrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crowd': typeof CrowdRoute
  '/journey': typeof JourneyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crowd': typeof CrowdRoute
  '/journey': typeof JourneyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crowd': typeof CrowdRoute
  '/journey': typeof JourneyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crowd' | '/journey' | '/map' | '/profile' | '/routes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crowd' | '/journey' | '/map' | '/profile' | '/routes'
  id: '__root__' | '/' | '/crowd' | '/journey' | '/map' | '/profile' | '/routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrowdRoute: typeof CrowdRoute
  JourneyRoute: typeof JourneyRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  RoutesRoute: typeof RoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowd': {
      id: '/crowd'
      path: '/crowd'
      fullPath: '/crowd'
      preLoaderRoute: typeof CrowdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrowdRoute: CrowdRoute,
  JourneyRoute: JourneyRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  RoutesRoute: RoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
